### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yurrriq**
Fix map example: `s/+2/+1/`

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Haha, how am I getting pull requests on a project I started while sick literally 8 hours ago? :+1:

**Comment by cmeiklejohn** [comment]
Thanks! :+1:

**Comment by yurrriq** [comment]
:laughing: You :star:'d it and I follow you so it showed up in my feed, which I compulsively refresh. I'm excited to see where this goes!

**Comment by cmeiklejohn** [comment]
Hopefully somewhere interesting!  We'll see...

**Pull request merged**
